

## 
## Script for analyzing experiments. 
##
## INPUT: experiment-data.txt (generated by ACT-R)
## OUTPUT:
## 	   	   - EXPNAME-data.txt
## 				 - EXPNAME-results.txt
## 				 - EXPNAME-results.pdf
##

library(em2)
library(reshape)
library(ggplot2)


data <- read.table("experiment-data.txt", header=T)
expname <- data$exp[1]
fullname <- data$fullname[1]
data[data=="NIL"] <- NA

for(c in 8:12){
	if(mean(is.na(data[,c]))==1) data[,c] <- data$data
}
write.table(data, paste(expname,"-data.txt",sep=""))

data$AT <- NA
data$ET <- NA
data$timeout <- NA
data <- melt(data, id=c("exp","cond","sent","pos","roi","condroi","fullname"), measure=c("data","FPRT","FFD","TFT","RRT","RPD","fp_reg","skip","reread","ACC","AT","ET"))
colnames(data)[9] <- "M"
data$M <- as.numeric(data$M)
head(data)



##------------------------------------------------------------
## SOME HELPER FUNCTIONS
##------------------------------------------------------------

## Function for computing confidence intervals
ci <- function (x) 
{
	m <- mean(x, na.rm = TRUE)
	n <- length(x[!is.na(x)])
	s <- sd(x, na.rm = TRUE)
	upper <- m + qt(0.975, df = n - 1) * (s/sqrt(n))
	lower <- m + qt(0.025, df = n - 1) * (s/sqrt(n))
	return(data.frame(lower = lower, upper = upper))
}

rmsd <- function (obs, pred){
	sqrt(mean((obs - pred)^2, na.rm = TRUE))
}

## DATA CLEAN-UP
data.cleanup <- function(m){
	m <- subset(m, pos!=1 & word!="*")
	m$trial <- paste(m$exp, m$iteration, m$cond)
	(n.trials <- length(unique(m$trial)))
	m$trialpos <- paste(m$exp, m$iteration, m$cond, m$pos)
	(length(unique(m$trialpos)))
  # head(m)
	m$dupl <- duplicated(m$trialpos)
	dim(subset(m,dupl))[1]
	m <- subset(m, !dupl)
	return(m)
}


prefix=""

analyze <- function(prefix=""){

if(prefix=="") resultsfile <- paste(expname,"-results",sep="") else resultsfile <- paste(prefix,"results",sep="")

##------------------------------------------------------------
## READ SIMULATION DATA
##------------------------------------------------------------
f <- read.table(paste(prefix,"fixations.txt",sep=""), header=F)
colnames(f) <- c("exp","iteration","cond","pos","word","dur")
f$cond <- factor(f$cond)
# head(f)
summary(f)



##------------------------------------------------------------
## COMPUTE EYE MOVEMENT MEASURES
##------------------------------------------------------------
f$iteration <- as.factor(as.character(f$iteration))
etm <- with(f, em2(pos, dur, data.frame(exp, iteration, cond)))
colnames(etm)[4] <- "pos"

##
## ADDITIONAL MEASURES
##
## first-pass regression probability:
etm$fp_reg <- ifelse(etm$RBRC>0,1,0) 
## skipping prob.:
etm$skip<-ifelse(etm$FPRT==0,1,0)
## re-reading prob:
etm$reread<-ifelse(etm$RRT>0,1,0)
## re-fixation prob.:
etm$refix <- ifelse(etm$FPRT>etm$FFD,1,0)
# head(etm)

## re-add words:
dim(etm)
etm <- merge(etm, unique(f[,3:5]), by=c("cond","pos"))
dim(etm)






##------------------------------------------------------------
## READ ADDITIONAL INFO
##------------------------------------------------------------
m <- etm

## ATTACHMENT TIMES:
att <- read.table(paste(prefix,"attachments.txt",sep=""), header=F)
colnames(att) <- c("exp","iteration","cond","pos","word","AT")
att$cond <- factor(att$cond)
dim(m)
m <- merge(m, att[,-5], by=c("exp","iteration","cond","pos"), all.x=TRUE, all.y=TRUE)
dim(m)

## ENCODING TIMES:
enc <- read.table(paste(prefix,"enctimes.txt",sep=""), header=F)
colnames(enc) <- c("exp","iteration","cond","pos","word","ET","ecc","freq")
enc$cond <- factor(enc$cond)
enc$iteration <- factor(enc$iteration)
dim(m)
m <- merge(m, enc[-5], by=c("exp","iteration","cond","pos"), all.x=TRUE)
dim(m)

## TRIAL MESSAGES
msg <- read.table(paste(prefix,"trialmessages.txt",sep=""), header=F)
colnames(msg) <- c("exp","iteration","cond","pos","word","variable","value")

trialinfo <- subset(msg[,-c(4,5)], variable!="timeout" & variable!="regression")
trialinfo <- reshape(trialinfo, idvar = c("exp","iteration","cond"), timevar="variable", direction="wide")
colnames(trialinfo) <- gsub("value.","", colnames(trialinfo))
trialinfo <- droplevels(trialinfo)

## Merge with EM results
if(dim(trialinfo)[1]>0){
	dim(m)
	m <- merge(m, trialinfo, by=c("exp","iteration","cond"), all.x=TRUE)
	m$fail <- ifelse(is.na(m$fail), 0, 1)
	dim(m)
}else{m$fail<-0}

## TIMEOUTS:
tmo <- droplevels(subset(msg, variable=="timeout"))
colnames(tmo)[6:7] <- c("timeout", "tmo-eyloc")
tmo$timeout <- 1
dim(m)
m <- merge(m, tmo[,-5], by=c("exp","iteration","cond","pos"), all.x=TRUE)
dim(m)
m$timeout[is.na(m$timeout)] <- 0




##------------------------------------------------------------
## SUBJECT INFORMATION
##------------------------------------------------------------
if(file.exists(paste(prefix,"subjects.txt",sep=""))){
	subjects <- read.table(paste(prefix,"subjects.txt",sep=""), header=F)
	colnames(subjects) <- c("exp","subj","ga")
	smed <- median(subjects$ga)
	subjects$wmc <- as.factor(ifelse(subjects$ga<smed,"lowWMC","highWMC"))
	dim(m)
	m <- merge(m, subjects, by=c("exp"), all.x=T)
	dim(m)
	data <- merge(data, subjects, by=c("exp"), all.x=T)
	print(summary(subjects$wmc))
	print(summary(subjects$ga))
}else{
	m$subj = 1
	m$ga = 1
	m$wmc = 1
	data$wmc = 1
	data$wmc <- factor(data$wmc)
	m$wmc <- factor(m$wmc)
}





##------------------------------------------------------------
## REGIONS OF INTEREST
##------------------------------------------------------------
summary(factor(m$cond))
dim(m)
m <- merge(m, data[,c(2,4,5)], by=c("cond","pos"), all.x=TRUE)
dim(m)

summary(m$roi)
levels(m$roi)[length(levels(m$roi))+1] <- "n-"
levels(m$roi)[length(levels(m$roi))+1] <- "n+"
levels(m$roi)[length(levels(m$roi))+1] <- "other"
for(c in unique(data$cond)){
	s <- subset(data, cond==c)
	minp <- min(s$pos)
	maxp <- max(s$pos)
	m$roi[m$cond==c & m$pos<minp] <- "n-"
	m$roi[m$cond==c & m$pos>maxp] <- "n+"
}
m$roi[is.na(m$roi)] <- "other"



##------------------------------------------------------------
## CLEANUP
##------------------------------------------------------------
m <- data.cleanup(m)



##------------------------------------------------------------
## MEANS
##------------------------------------------------------------
## FAILURES
fail1 <- cast(m, exp+wmc+iteration+cond~., function(x) c(M=mean(x), N=length(x)), value="fail")
fail <- cast(fail1, wmc+cond~., function(x) c(M=mean(x), N=length(x)), value="M")
fail$SE <- sqrt(fail$M*(1-fail$M))/sqrt(fail$N)
fail$CI.lower <- fail$M + qt(.025, df=fail$N-1) * fail$SE
fail$CI.upper <- fail$M + qt(.975, df=fail$N-1) * fail$SE
colnames(fail)[3] <- "fail"


## Exclude failed trials
m.all <- m
m <- subset(m, fail==0)


## TIMES:
mlt <- melt(subset(m), id=c("roi","pos","cond","wmc"), measure=c("SFD","FFD","FPRT","TFT","RPD","RRT","AT","ET"), na.rm = TRUE)
## by roi
cst <- cast(subset(mlt, !variable%in%c("RRT","RPD") & !is.na(roi) & value>0), variable+roi+cond+wmc ~ ., function(x) c(M=mean(x), SE=sd(x, na.rm=T)/sqrt(length(x)), N=length(x), CI=ci(x)))
try(cst <- cast(subset(mlt, !is.na(roi) & value>0), variable+roi+cond+wmc ~ ., function(x) c(M=mean(x), SE=sd(x, na.rm=T)/sqrt(length(x)), N=length(x), CI=ci(x))))
means.t <- cst
## by pos
cst <- cast(subset(mlt, value>0 & variable%in%c("FPRT","TFT","RPD","RRT","AT","ET")), variable+pos+cond+wmc ~ ., function(x) c(M=mean(x), N=length(x)))
cst$SE <- NA
cst$CI.lower=NA
cst$CI.upper=NA
try(cst <- cast(subset(mlt, value>0 & variable%in%c("FPRT","TFT","RPD","RRT","AT","ET")), variable+pos+cond+wmc ~ ., function(x) c(M=mean(x), SE=sd(x)/sqrt(length(x)), N=length(x), CI=ci(x))))
means.pos.t <- cst

## PROBABILITIES:
mlt <- melt(subset(m), id=c("roi","pos","cond","wmc"), measure=c("refix","reread","fp_reg","skip","timeout"), na.rm=T)
## by roi
cst <- cast(subset(mlt, !is.na(roi)), variable+roi+cond+wmc ~ ., function(x) c(M=mean(x), N=length(x)))
cst$SE <- sqrt(cst$M*(1-cst$M))/sqrt(cst$N)
cst$CI.lower <- cst$M + qt(.025, df=cst$N-1) * cst$SE
cst$CI.upper <- cst$M + qt(.975, df=cst$N-1) * cst$SE
means.p <- cst
## by pos
cst <- cast(subset(mlt), variable+pos+cond+wmc ~ ., function(x) c(M=mean(x), N=length(x)))
cst$SE <- sqrt(cst$M*(1-cst$M))/sqrt(cst$N)
cst$CI.lower <- cst$M + qt(.025, df=cst$N-1) * cst$SE
cst$CI.upper <- cst$M + qt(.975, df=cst$N-1) * cst$SE
means.pos.p <- cst


means <- rbind(means.t,means.p)
summary(means)
means.pos <- rbind(means.pos.t,means.pos.p)

write.table(means, paste(resultsfile,".txt",sep=""))
save(m, means, file="m.Rd")



##------------------------------------------------------------
## PLOTS
##------------------------------------------------------------
dodge <- position_dodge(width=.9)
dodge2 <- position_dodge(width=.6)
dodge3 <- position_dodge(width=.1)

pdf(paste(resultsfile,".pdf",sep=""), onefile=T)

## READING TIME
print(pr <- ggplot(subset(means, (M!=0 & variable%in%c("FFD","FPRT","RPD","TFT","RRT","AT"))), aes(roi, M, col=cond, shape=wmc))
	+ geom_point(position=dodge2)
	+ geom_errorbar(aes(max=CI.upper, min=CI.lower, width=0), position=dodge2)
	+ xlab("")
	+ ylab("Mean duration in ms")
	+ coord_cartesian()
	+ ggtitle(paste(fullname, " - Reading times"))
	+ theme_bw(base_size=10)
# + facet_grid(variable~.)
	+ facet_wrap(~variable, ncol=2, scales="free")
	+ geom_point(data=subset(data, M!=0 & variable%in%c("FFD","FPRT","RPD","TFT","RRT","AT")),shape=4, position=dodge3) #color=c("gray30"))
	)
	# ggsave(pr, file=paste(prefix,"plot-reading-times.pdf",sep=""), height=7, width=9)

## PROBABILITIES
print(pp <- ggplot(subset(means, variable%in%c("reread","fp_reg","refix", "skip","timeout")), 
	aes(roi, M, fill=cond))
+ geom_bar(stat="identity", position=dodge)
+ geom_linerange(aes(max=CI.upper, min=CI.lower, width=0), position=dodge)
+ ggtitle("Model probabilities")
+ theme_bw(base_size=10)
+ facet_wrap(variable ~ wmc, ncol=2, scales="free")
+ geom_point(data=subset(data, variable%in%c("reread","fp_reg","refix", "skip","timeout")),shape=4, position=dodge) #color=c("gray30"))
)
	# ggsave(pp, file=paste(prefix,"plot-probabilities.pdf",sep=""), height=7, width=9)


## FAILURES
print(pf <- ggplot(fail, 
	aes(cond, fail, fill=wmc))
+ geom_bar(stat="identity", position=dodge)
+ geom_errorbar(aes(max=CI.upper, min=CI.lower, width=0), position=dodge)
# + ylim(0,1)
+ coord_cartesian(ylim=c(0,1))
+ xlab("")
+ ylab("Probability")
+ theme_classic(base_size=10)
+ ggtitle("Model failure")
)
	# ggsave(pf, file=paste(prefix,"plot-failures.pdf",sep=""))


## WMC
boxplot(as.numeric(m$ga), main="WMC")


## OVERVIEW RT
print(por <- ggplot(subset(means.pos, (M!=0 & variable%in%c("AT","ET","FPRT","TFT","RRT"))), aes(pos, M, col=cond, linetype=wmc, shape=wmc))
	+ geom_point() + geom_line()
	+ geom_errorbar(aes(max=CI.upper, min=CI.lower, width=0))
	+ xlab("")
	+ ylab("Mean duration in ms")
	+ coord_cartesian()
	+ ggtitle("Model overview RT")
	+ theme_bw(base_size=10)
# + facet_grid(variable~.)
	+ facet_wrap(~variable, ncol=1, scales="free")
	+ theme(legend.position="bottom")
	+ geom_point(data=subset(data, M!=0 & variable%in%c("FPRT","TFT","RRT","AT","ET")),shape=4, position=dodge3) #color=c("gray30"))
		)
# ggsave(por, file=paste(prefix,"plot-overview1.pdf",sep=""), height=9, width=9)

## OVERVIEW PROB
print(pop <- ggplot(subset(means.pos, variable%in%c("reread","fp_reg","refix", "skip","timeout")), 
	aes(pos, M, col=cond, linetype=wmc, shape=wmc))
+ geom_line() + geom_point()
+ geom_linerange(aes(max=CI.upper, min=CI.lower, width=0))
+ ggtitle("Model overview Prob")
+ theme_bw(base_size=10)
+ facet_wrap(~variable, ncol=1, scales="free")
+ theme(legend.position="bottom")
+ geom_point(data=subset(data, variable%in%c("reread","fp_reg","refix", "skip","timeout")),shape=4, position=dodge) #color=c("gray30"))
)
# ggsave(pop, file=paste(prefix,"plot-overview2.pdf",sep=""), height=9, width=9)



##------------------------------------------------------------
## SCANPATHS
##------------------------------------------------------------

## PLOT SCANPATH OF RANDOM TRIAL ##
i <- sample(unique(f$iteration),1)
e <- sample(unique(f$exp),1)
t1 <- subset(f, iteration%in%i & exp%in%e)
t1$index <- NA
for(i in unique(t1$iteration)){
	for(c in t1$cond){
		s <- (t1$iteration==i & t1$cond==c)
		t1$index[s] <- 1:length(t1$pos[s])
	}
}
(psc <- ggplot(t1, aes(index, pos, group=cond, col=cond)) + geom_point(aes(size=dur)) + geom_line() 
	+ scale_y_discrete(labels=min(t1$pos):max(t1$pos)) 
	+ ggtitle(i))


## PLOT SCANPATH OF 7 RANDOM TRIALS ##
i <- sample(unique(f$iteration),7)
e <- sample(unique(f$exp),1)
t1 <- subset(f, iteration%in%i & exp%in%e)
t1$index <- NA
for(i in unique(t1$iteration)){
	for(c in t1$cond){
		s <- (t1$iteration==i & t1$cond==c)
		t1$index[s] <- 1:length(t1$pos[s])
	}
}
(psc7 <- ggplot(t1, aes(index, pos, group=cond, col=cond)) + geom_point(aes(size=dur)) + geom_line() + facet_grid(.~iteration) + scale_y_discrete(labels=min(t1$pos):max(t1$pos)) + theme(legend.position="bottom"))



##------------------------------------------------------------
## FIT WITH THE DATA
##------------------------------------------------------------
model <- subset(means,variable=="TFT" & !roi%in%c("n-","n+","other"))
colnames(model)[5] <- "model"
human <- subset(data,variable=="data" & !roi%in%c("n-","n+","other"))
colnames(human)[9] <- "data"
result <- merge(model, human[,c(2,5,9)], by=c("cond","roi"))
result

(error <- rmsd(result$data,result$model))
(r <- cor(result$data,result$model))
(score <- error-100*r)

effect1 <- 0
effect2 <- 0
effscore <- 0

par(mfrow=c(1,3))
barplot(error,main="Root-mean-squared error (TFT)",ylim=c(0,error*1.5))
barplot(r,main="Correlation (TFT)", ylim=c(-1,1))
plot(score,main="Score",cex=2, pch=16)

dev.off()



	# return(list(m=m, means, error=error,r=r,score=score, effect1=effect1, effect2=effect2, effscore=effscore))
}

analyze()
